### ISSUE TITLE
Debug Gravity Compensation

### ISSUE THREAD

**Issue by egordon** [personalrobotics/geodude_ros2#4]
Per #3 , we know that gravity compensation is imperfect (at least for J4 and J5). Not urgent, but it should be debugged, potentially by adding new poses.

**Comment by atharva620** [comment]
Approach to improve compensation for J4 and J5:

1. Started by adding more poses to the config file located at `etc/barrett/calibration.conf` since `gravitycal.cpp` reads from the etc directory by default. (Can be changed, for instance to read from geodude_ros2/geodude_hardware/config/calibration.conf) 
2. While adding poses, refer [https://support.barrett.com/wiki/WAM/Calibration](url) and add poses symmetrically such that they can be approached by the arm twice, from above and below the horizontal axis of J1.
3. In this case, since J4 and J5 were under-compensated, 8 more poses were added (with emphasis on covering the joint ranges of J4 and J5) making a total of 24 poses for gravity compensation.

Testing the gravity compensation:
The best way to test if gravity compensation is successful is to run any libbarrett example which has a `wam.gravityCompensate()` function. Suggested example is `ex02_hold_position.cpp` which allows the user to fully stretch the arm and lock joints/end-effector on command. Before running the example, please keep the E-STOP handy because if the compensation is poor and the arm is torque controlled, it might yield to gravity or bump into anything nearby.

Common pitfalls:

1. Depending upon how the WAM is mounted, the world to base transform changes and can be specified in `etc/barrett/calibration.conf` this could lead to failed compensation since libbarrett's gravitycal.cpp asumes that the WAM is mounted horizontally.
2. Some poses may cause a torque fault. Although a concrete cause could not be found, it is possible that the specified pose has a joint value exceeding limits. Since the hardware has no sense of that, it continues to exert torque, possibly causing the torque fault.
3. If there are any syntactical errors in the configuration files, the calibration will error out saying that the calibration file was not found. Touching the WAM will also cause calibration failure.
